apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  type: NodePort
  ports:
  - name: java-service
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: java-app
